### ISSUE TITLE
Issue installing on React Native > 0.60

### ISSUE THREAD

**Issue by vabanagas** [lg2/react-native-eddystone#4]
I was unable to install the library without making changes to the podspec file. I had to rename the file from "Eddystone.podspec" to "RNReactNativeEddystone.podspec" and added a homepage URL of "https://github.com/lg2/react-native-eddystone". This allowed me to use `pod install` to link this library.

Version: 0.1.2
React Native Version: 0.60.5

**Comment by nicholasc** [comment]
I apologize for the delay in fixing this. I have gone ahead and made the changes to the podspec file and published a new version (v0.1.4). Let me know if you see anything else.

Thank you for submitting this issue!
