### ISSUE TITLE
Attempt to invoke virtual method 'void android.bluetooth.le.BluetoothScanner.startScan(java.util.List, android.bluetooth.le.ScanSettings,android.bluetooth.le.ScanCallback)' on a null object reference

### ISSUE THREAD

**Issue by wolfag** [lg2/react-native-eddystone#7]
Hi, Please help me resolve above issue, I got above issue when I ran your example.
This is my env:

> System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 264.87 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.5.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
      System Images: android-16 | ARM EABI v7a, android-23 | ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.6 => 0.60.6 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

Thank you!

**Comment by nicholasc** [comment]
Hello @wolfag,

Thank you for submitting this issue! I will take a look as soon as I can get my hands on a computer.

**Comment by nicholasc** [comment]
Hi @wolfag,

Would you be able to provide a repository that would help me reproduce this issue? 

Thank you.

**Comment by wolfag** [comment]
Hi @nicholasc ,
Please see in [https://github.com/wolfag/demo_beacon](url).

Thank you.

**Comment by nicholasc** [comment]
Hi @wolfag,

Just a quick update here. It seems that when Bluetooth is deactivated on Android you must the user to activate it now or else the bluetooth scanner object is returned null. I started implementing the solution but it seem to crash the application at some point. I'll keep working on this and hopefully will publish a fix by the end of the week.

Thanks!

**Comment by nicholasc** [comment]
I commited changes that fix this issue and gone ahead and published v0.1.5 on npm. Thank you for submitting this and enjoy!

**Comment by wolfag** [comment]
thank @nicholasc ,
I will check now.
